# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign2or.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QScrollArea, QWidget, QVBoxLayout, QGridLayout
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QSizePolicy




class Ui_AuraEdit(object):
    def setupUi(self, AuraEdit):
          # Explicitly set the window title
        AuraEdit.setWindowTitle("AuraEdit")
        AuraEdit.setObjectName("AuraEdit")
        AuraEdit.setWindowModality(QtCore.Qt.WindowModal)
        AuraEdit.resize(600, 200)
        AuraEdit.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"QMenuBar::item {\n"
"    color: white; /* Set the color of the menu text */\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(AuraEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tools_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_widget.sizePolicy().hasHeightForWidth())
        self.tools_widget.setSizePolicy(sizePolicy)
        self.tools_widget.setMinimumSize(QtCore.QSize(60, 890))
        self.tools_widget.setMaximumSize(QtCore.QSize(60, 890))
        self.tools_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.tools_widget.setObjectName("tools_widget")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tools_widget)
        self.verticalLayout_22.setContentsMargins(5, 7, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        spacerItem = QtWidgets.QSpacerItem(2, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_22.addItem(spacerItem)
        self.logo1 = QtWidgets.QLabel(self.tools_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo1.sizePolicy().hasHeightForWidth())
        self.logo1.setSizePolicy(sizePolicy)
        self.logo1.setMinimumSize(QtCore.QSize(45, 45))
        self.logo1.setMaximumSize(QtCore.QSize(45, 45))
        self.logo1.setStyleSheet("QLabel:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QLabel{\n"
"   height:10px;\n"
"}")
        self.logo1.setText("")
        self.logo1.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo1.setScaledContents(True)
        self.logo1.setObjectName("logo1")
        self.verticalLayout_22.addWidget(self.logo1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(0, 15, -1, -1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
#         self.size1_pushButton = QtWidgets.QPushButton(self.tools_widget)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.size1_pushButton.sizePolicy().hasHeightForWidth())
#         self.size1_pushButton.setSizePolicy(sizePolicy)
#         self.size1_pushButton.setStyleSheet("QWidget{\n"
# "    background-color: rgb(53, 53, 53);\n"
# "}\n"
# "QPushButton:hover{\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}\n"
# "QPushButton{\n"
# "    height:10px;\n"
# "}\n"
# "")
#         self.size1_pushButton.setText("")
#         icon = QtGui.QIcon()
#         icon.addPixmap(QtGui.QPixmap("icon/selectcursor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.size1_pushButton.setIcon(icon)
#         self.size1_pushButton.setIconSize(QtCore.QSize(30, 30))
#         self.size1_pushButton.setCheckable(True)
#         self.size1_pushButton.setAutoExclusive(True)
#         self.size1_pushButton.setFlat(True)
#         self.size1_pushButton.setObjectName("size1_pushButton")
#         self.verticalLayout_17.addWidget(self.size1_pushButton)
        self.adjust1_pushButton = QtWidgets.QPushButton(self.tools_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adjust1_pushButton.sizePolicy().hasHeightForWidth())
        self.adjust1_pushButton.setSizePolicy(sizePolicy)
        self.adjust1_pushButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}")
        self.adjust1_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/adjust.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adjust1_pushButton.setIcon(icon1)
        self.adjust1_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.adjust1_pushButton.setCheckable(True)
        self.adjust1_pushButton.setAutoExclusive(True)
        self.adjust1_pushButton.setFlat(True)
        self.adjust1_pushButton.setObjectName("adjust1_pushButton")
        self.verticalLayout_17.addWidget(self.adjust1_pushButton)
#         self.select1_pushButton = QtWidgets.QPushButton(self.tools_widget)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.select1_pushButton.sizePolicy().hasHeightForWidth())
#         self.select1_pushButton.setSizePolicy(sizePolicy)
#         self.select1_pushButton.setStyleSheet("QPushButton:hover{\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}")
#         self.select1_pushButton.setText("")
#         icon2 = QtGui.QIcon()
#         icon2.addPixmap(QtGui.QPixmap("icon/icons8-page-size-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.select1_pushButton.setIcon(icon2)
#         self.select1_pushButton.setIconSize(QtCore.QSize(30, 30))
#         self.select1_pushButton.setCheckable(True)
#         self.select1_pushButton.setAutoExclusive(True)
#         self.select1_pushButton.setFlat(True)
#         self.select1_pushButton.setObjectName("select1_pushButton")
#         self.verticalLayout_17.addWidget(self.select1_pushButton)
        self.retouch1_pushButton = QtWidgets.QPushButton(self.tools_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.retouch1_pushButton.sizePolicy().hasHeightForWidth())
        self.retouch1_pushButton.setSizePolicy(sizePolicy)
        self.retouch1_pushButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}")
        self.retouch1_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.retouch1_pushButton.setIcon(icon3)
        self.retouch1_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.retouch1_pushButton.setCheckable(True)
        self.retouch1_pushButton.setAutoExclusive(True)
        self.retouch1_pushButton.setFlat(True)
        self.retouch1_pushButton.setObjectName("retouch1_pushButton")
        self.verticalLayout_17.addWidget(self.retouch1_pushButton)
        self.quickaction1_pushButton = QtWidgets.QPushButton(self.tools_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickaction1_pushButton.sizePolicy().hasHeightForWidth())
        self.quickaction1_pushButton.setSizePolicy(sizePolicy)
        self.quickaction1_pushButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}")
        self.quickaction1_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/booster.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quickaction1_pushButton.setIcon(icon4)
        self.quickaction1_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.quickaction1_pushButton.setCheckable(True)
        self.quickaction1_pushButton.setAutoExclusive(True)
        self.quickaction1_pushButton.setFlat(True)
        self.quickaction1_pushButton.setObjectName("quickaction1_pushButton")
        self.verticalLayout_17.addWidget(self.quickaction1_pushButton)
        self.paint1_pushButton = QtWidgets.QPushButton(self.tools_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paint1_pushButton.sizePolicy().hasHeightForWidth())
        self.paint1_pushButton.setSizePolicy(sizePolicy)
        self.paint1_pushButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}")
        self.paint1_pushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/paint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paint1_pushButton.setIcon(icon5)
        self.paint1_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.paint1_pushButton.setCheckable(True)
        self.paint1_pushButton.setAutoExclusive(True)
        self.paint1_pushButton.setFlat(True)
        self.paint1_pushButton.setObjectName("paint1_pushButton")
        self.verticalLayout_17.addWidget(self.paint1_pushButton)
        self.transform1_pushButton = QtWidgets.QPushButton(self.tools_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transform1_pushButton.sizePolicy().hasHeightForWidth())
        self.transform1_pushButton.setSizePolicy(sizePolicy)
        self.transform1_pushButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}")
        self.transform1_pushButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/transform.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transform1_pushButton.setIcon(icon6)
        self.transform1_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.transform1_pushButton.setCheckable(True)
        self.transform1_pushButton.setAutoExclusive(True)
        self.transform1_pushButton.setFlat(True)
        self.transform1_pushButton.setObjectName("transform1_pushButton")
        self.verticalLayout_17.addWidget(self.transform1_pushButton)
        self.text1_pushButton = QtWidgets.QPushButton(self.tools_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text1_pushButton.sizePolicy().hasHeightForWidth())
        self.text1_pushButton.setSizePolicy(sizePolicy)
        self.text1_pushButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}")
        self.text1_pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/text (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.text1_pushButton.setIcon(icon7)
        self.text1_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.text1_pushButton.setCheckable(True)
        self.text1_pushButton.setAutoExclusive(True)
        self.text1_pushButton.setFlat(True)
        self.text1_pushButton.setObjectName("text1_pushButton")
        self.verticalLayout_17.addWidget(self.text1_pushButton)
#         self.shape1_pushButton = QtWidgets.QPushButton(self.tools_widget)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.shape1_pushButton.sizePolicy().hasHeightForWidth())
#         self.shape1_pushButton.setSizePolicy(sizePolicy)
#         self.shape1_pushButton.setStyleSheet("QPushButton:hover{\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}")
#         self.shape1_pushButton.setText("")
#         icon8 = QtGui.QIcon()
#         icon8.addPixmap(QtGui.QPixmap("icon/shapes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.shape1_pushButton.setIcon(icon8)
#         self.shape1_pushButton.setIconSize(QtCore.QSize(30, 30))
#         self.shape1_pushButton.setCheckable(True)
#         self.shape1_pushButton.setAutoExclusive(True)
#         self.shape1_pushButton.setFlat(True)
#         self.shape1_pushButton.setObjectName("shape1_pushButton")
#         self.verticalLayout_17.addWidget(self.shape1_pushButton)
        self.verticalLayout_22.addLayout(self.verticalLayout_17)
        spacerItem1 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem1)
        self.gridLayout.addWidget(self.tools_widget, 0, 0, 1, 1)
        self.tools_widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_widget_2.sizePolicy().hasHeightForWidth())
        self.tools_widget_2.setSizePolicy(sizePolicy)
        self.tools_widget_2.setMinimumSize(QtCore.QSize(250, 940))
        self.tools_widget_2.setMaximumSize(QtCore.QSize(250, 940))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tools_widget_2.setFont(font)
        self.tools_widget_2.setStyleSheet("QWidget{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(53, 53, 53);\n"
"}\n"
"QPushBotton{\n"
"   height:10px;\n"
"   border:none;\n"
"}")
        self.tools_widget_2.setObjectName("tools_widget_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tools_widget_2)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo2 = QtWidgets.QLabel(self.tools_widget_2)
        self.logo2.setMinimumSize(QtCore.QSize(45, 45))
        self.logo2.setMaximumSize(QtCore.QSize(45, 45))
        self.logo2.setStyleSheet("QLabel:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"Qlabel{\n"
"height:10px;\n"
"}")
        self.logo2.setText("")
        self.logo2.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo2.setScaledContents(True)
        self.logo2.setObjectName("logo2")
        self.horizontalLayout_2.addWidget(self.logo2)
        self.logo_name = QtWidgets.QLabel(self.tools_widget_2)
        self.logo_name.setMinimumSize(QtCore.QSize(125, 60))
        self.logo_name.setMaximumSize(QtCore.QSize(125, 60))
        self.logo_name.setStyleSheet("QLabel:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}")
        self.logo_name.setText("")
        self.logo_name.setPixmap(QtGui.QPixmap("logo_n.png"))
        self.logo_name.setScaledContents(True)
        self.logo_name.setObjectName("logo_name")
        self.horizontalLayout_2.addWidget(self.logo_name)
        spacerItem2 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_2)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_16.setSpacing(22)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        # self.size_frame_2 = QtWidgets.QFrame(self.tools_widget_2)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # self.size_frame_2.setFont(font)
        # self.size_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.size_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.size_frame_2.setObjectName("size_frame_2")
        # self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.size_frame_2)
        # self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        # self.verticalLayout_5.setSpacing(0)
        # self.verticalLayout_5.setObjectName("verticalLayout_5")
#         self.size2_pushButton = QtWidgets.QPushButton(self.size_frame_2)
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(8)
#         font.setBold(True)
#         font.setWeight(75)
#         self.size2_pushButton.setFont(font)
#         self.size2_pushButton.setStyleSheet("QPushButton{\n"
# "border:none;\n"
# " outline: none;\n"
# "}\n"
# "QPushButton {\n"
# "    height:25px;\n"
# "    text-align: left;}\n"
# "QPushButton:hover{\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}")
#         icon9 = QtGui.QIcon()
#         icon9.addPixmap(QtGui.QPixmap("icon/icons8-chevron-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
#         icon9.addPixmap(QtGui.QPixmap("icon/selectcursor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.size2_pushButton.setIcon(icon9)
#         self.size2_pushButton.setIconSize(QtCore.QSize(30, 30))
#         self.size2_pushButton.setCheckable(True)
#         self.size2_pushButton.setAutoExclusive(False)
#         self.size2_pushButton.setFlat(True)
#         self.size2_pushButton.setChecked(True)
#         self.size2_pushButton.setObjectName("size2_pushButton")
#         self.verticalLayout_5.addWidget(self.size2_pushButton)
#         self.size_dropdown = QtWidgets.QFrame(self.size_frame_2)
#         self.size_dropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.size_dropdown.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.size_dropdown.setObjectName("size_dropdown")
#         self.verticalLayout = QtWidgets.QVBoxLayout(self.size_dropdown)
#         self.verticalLayout.setContentsMargins(0, 5, 0, 0)
#         self.verticalLayout.setSpacing(4)
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.move = QtWidgets.QPushButton(self.size_dropdown)
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(8)
#         self.move.setFont(font)
#         self.move.setStyleSheet("QPushButton {\n"
# "    text-align: left;\n"
# "    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
# "     height:25px;\n"
# "}\n"
# "QPushButton:hover{\n"
# "    color: rgb(255, 167, 135);\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}\n"
# "QPushButton{\n"
# "border:none;\n"
# " outline: none;\n"
# "}")
#         icon10 = QtGui.QIcon()
#         icon10.addPixmap(QtGui.QPixmap("icon/icons8-move-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.move.setIcon(icon10)
#         self.move.setIconSize(QtCore.QSize(30, 30))
#         self.move.setCheckable(True)
#         self.move.setFlat(True)
#         self.move.setObjectName("move")
#         self.verticalLayout.addWidget(self.move)
#         self.crop = QtWidgets.QPushButton(self.size_dropdown)
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(8)
#         self.crop.setFont(font)
#         self.crop.setStyleSheet("QPushButton {\n"
# "     height:25px;\n"
# "    text-align: left;\n"
# "    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
# "}\n"
# "\n"
# "QPushButton:hover{\n"
# "    color: rgb(255, 167, 135);\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}\n"
# "QPushButton{\n"
# "border:none;\n"
# " outline: none;\n"
# "}")
#         icon11 = QtGui.QIcon()
#         icon11.addPixmap(QtGui.QPixmap("icon/icons8-crop-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.crop.setIcon(icon11)
#         self.crop.setIconSize(QtCore.QSize(25, 25))
#         self.crop.setCheckable(True)
#         self.crop.setFlat(True)
#         self.crop.setObjectName("crop")
#         self.verticalLayout.addWidget(self.crop)
#         self.resizing = QtWidgets.QPushButton(self.size_dropdown)
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(8)
#         self.resizing.setFont(font)
#         self.resizing.setStyleSheet("QPushButton {\n"
# "    text-align: left;\n"
# "    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
# "    height:25px;\n"
# "}\n"
# "QPushButton:hover{\n"
# "    color: rgb(255, 167, 135);\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}\n"
# "QPushButton{\n"
# "border:none;\n"
# " outline: none;\n"
# "}")
#         icon12 = QtGui.QIcon()
#         icon12.addPixmap(QtGui.QPixmap("icon/icons8-resize-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.resizing.setIcon(icon12)
#         self.resizing.setIconSize(QtCore.QSize(30,30 ))
#         self.resizing.setCheckable(True)
#         self.resizing.setFlat(True)
#         self.resizing.setObjectName("resizing")
#         self.verticalLayout.addWidget(self.resizing)
        # self.verticalLayout_5.addWidget(self.size_dropdown)
        # self.verticalLayout_16.addWidget(self.size_frame_2)
        self.Adjust_frame = QtWidgets.QFrame(self.tools_widget_2)
        self.Adjust_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Adjust_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Adjust_frame.setObjectName("Adjust_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Adjust_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.adjust2_pushButton = QtWidgets.QPushButton(self.Adjust_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.adjust2_pushButton.setFont(font)
        self.adjust2_pushButton.setStyleSheet("\n"
"QPushButton {\n"
"    text-align: left;\n"
"     height:25px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icon/icons8-chevron-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon13.addPixmap(QtGui.QPixmap("icon/adjust.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adjust2_pushButton.setIcon(icon13)
        self.adjust2_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.adjust2_pushButton.setCheckable(True)
        self.adjust2_pushButton.setAutoExclusive(False)
        self.adjust2_pushButton.setFlat(True)
        self.adjust2_pushButton.setChecked(True)
        self.adjust2_pushButton.setObjectName("adjust2_pushButton")
        self.verticalLayout_6.addWidget(self.adjust2_pushButton)
        self.adjust_dropdown = QtWidgets.QFrame(self.Adjust_frame)
        self.adjust_dropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.adjust_dropdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.adjust_dropdown.setObjectName("adjust_dropdown")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.adjust_dropdown)
        self.verticalLayout_4.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.brightness = QtWidgets.QPushButton(self.adjust_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.brightness.setFont(font)
        self.brightness.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"     height:25px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icon/icons8-brightness-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brightness.setIcon(icon14)
        self.brightness.setIconSize(QtCore.QSize(30, 30))
        self.brightness.setCheckable(True)
        self.brightness.setFlat(True)
        self.brightness.setObjectName("brightness")
        self.verticalLayout_4.addWidget(self.brightness)
        self.saturation = QtWidgets.QPushButton(self.adjust_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.saturation.setFont(font)
        self.saturation.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"     height:25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icon/icons8-saturation-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saturation.setIcon(icon15)
        self.saturation.setIconSize(QtCore.QSize(25, 25))
        self.saturation.setCheckable(True)
        self.saturation.setFlat(True)
        self.saturation.setObjectName("saturation")
        self.verticalLayout_4.addWidget(self.saturation)
        self.verticalLayout_6.addWidget(self.adjust_dropdown)
        self.verticalLayout_16.addWidget(self.Adjust_frame)
#         self.select_frame_8 = QtWidgets.QFrame(self.tools_widget_2)
#         self.select_frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.select_frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.select_frame_8.setObjectName("select_frame_8")
#         self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.select_frame_8)
#         self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
#         self.verticalLayout_19.setSpacing(0)
#         self.verticalLayout_19.setObjectName("verticalLayout_19")
#         self.select2_pushButton = QtWidgets.QPushButton(self.select_frame_8)
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(8)
#         font.setBold(True)
#         font.setWeight(75)
#         self.select2_pushButton.setFont(font)
#         self.select2_pushButton.setStyleSheet("QPushButton {\n"
# "     height:25px;\n"
# "    text-align: left;}\n"
# "QPushButton:hover{\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}\n"
# "QPushButton{\n"
# "border:none;\n"
# " outline: none;\n"
# "}")
#         icon16 = QtGui.QIcon()
#         icon16.addPixmap(QtGui.QPixmap("icon/icons8-chevron-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
#         icon16.addPixmap(QtGui.QPixmap("icon/icons8-page-size-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.select2_pushButton.setIcon(icon16)
#         self.select2_pushButton.setIconSize(QtCore.QSize(25, 25))
#         self.select2_pushButton.setCheckable(True)
#         self.select2_pushButton.setAutoExclusive(False)
#         self.select2_pushButton.setFlat(True)
#         self.select2_pushButton.setChecked(True)
#         self.select2_pushButton.setObjectName("select2_pushButton")
#         self.verticalLayout_19.addWidget(self.select2_pushButton)
#         self.select_dropdown = QtWidgets.QFrame(self.select_frame_8)
#         self.select_dropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.select_dropdown.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.select_dropdown.setObjectName("select_dropdown")
#         self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.select_dropdown)
#         self.verticalLayout_8.setContentsMargins(0, 5, 0, 0)
#         self.verticalLayout_8.setSpacing(4)
#         self.verticalLayout_8.setObjectName("verticalLayout_8")
#         self.select_subject = QtWidgets.QPushButton(self.select_dropdown)
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(8)
#         self.select_subject.setFont(font)
#         self.select_subject.setStyleSheet("QPushButton {\n"
# "     height:25px;\n"
# "    text-align: left;\n"
# "    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
# "}\n"
# "QPushButton:hover{\n"
# "    color: rgb(255, 167, 135);\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}\n"
# "QPushButton{\n"
# "border:none;\n"
# " outline: none;\n"
# "}")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icon/icons8-invert-selection-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.select_subject.setIcon(icon17)
#         self.select_subject.setIconSize(QtCore.QSize(30, 30))
#         self.select_subject.setCheckable(True)
#         self.select_subject.setFlat(True)
#         self.select_subject.setObjectName("select_subject")
#         self.verticalLayout_8.addWidget(self.select_subject)
#         self.object_selection = QtWidgets.QPushButton(self.select_dropdown)
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(8)
#         self.object_selection.setFont(font)
#         self.object_selection.setStyleSheet("QPushButton {\n"
# "     height:25px;\n"                                            
# "    text-align: left;\n"
# "    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
# "}\n"
# "QPushButton:hover{\n"
# "    color: rgb(255, 167, 135);\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}\n"
# "QPushButton{\n"
# "border:none;\n"
# " outline: none;\n"
# "}")
#         icon18 = QtGui.QIcon()
#         icon18.addPixmap(QtGui.QPixmap("icon/icons8-object-rotation-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.object_selection.setIcon(icon18)
#         self.object_selection.setIconSize(QtCore.QSize(30, 30))
#         self.object_selection.setCheckable(True)
#         self.object_selection.setFlat(True)
#         self.object_selection.setObjectName("object_selection")
#         self.verticalLayout_8.addWidget(self.object_selection)
#         self.verticalLayout_19.addWidget(self.select_dropdown)
#         self.verticalLayout_16.addWidget(self.select_frame_8)
        self.retouch_frame_9 = QtWidgets.QFrame(self.tools_widget_2)
        self.retouch_frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.retouch_frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.retouch_frame_9.setObjectName("retouch_frame_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.retouch_frame_9)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.retouch2_pushButton = QtWidgets.QPushButton(self.retouch_frame_9)
        self.retouch2_pushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.retouch2_pushButton.setFont(font)
        self.retouch2_pushButton.setStyleSheet("QPushButton {\n"
"     height:25px;\n"                                               
"    text-align: left;}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("icon/icons8-chevron-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon19.addPixmap(QtGui.QPixmap("icon/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.retouch2_pushButton.setIcon(icon19)
        self.retouch2_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.retouch2_pushButton.setCheckable(True)
        self.retouch2_pushButton.setAutoExclusive(True)
        self.retouch2_pushButton.setFlat(True)
        self.retouch2_pushButton.setChecked(True)
        self.retouch2_pushButton.setObjectName("retouch2_pushButton")
        self.verticalLayout_13.addWidget(self.retouch2_pushButton)
        self.retouch_dropdown = QtWidgets.QFrame(self.retouch_frame_9)
        self.retouch_dropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.retouch_dropdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.retouch_dropdown.setObjectName("retouch_dropdown")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.retouch_dropdown)
        self.verticalLayout_7.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_7.setSpacing(4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lighten = QtWidgets.QPushButton(self.retouch_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lighten.setFont(font)
        self.lighten.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("icon/icons8-color-wheel-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lighten.setIcon(icon20)
        self.lighten.setIconSize(QtCore.QSize(30, 30))
        self.lighten.setCheckable(True)
        self.lighten.setFlat(True)
        self.lighten.setObjectName("lighten")
        self.verticalLayout_7.addWidget(self.lighten)
        self.darken = QtWidgets.QPushButton(self.retouch_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.darken.setFont(font)
        self.darken.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("icon/icons8-color-mode-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.darken.setIcon(icon21)
        self.darken.setIconSize(QtCore.QSize(30, 30))
        self.darken.setCheckable(True)
        self.darken.setFlat(True)
        self.darken.setObjectName("darken")
        self.verticalLayout_7.addWidget(self.darken)
        self.verticalLayout_13.addWidget(self.retouch_dropdown)
        self.verticalLayout_16.addWidget(self.retouch_frame_9)
        self.quickaction_frame = QtWidgets.QFrame(self.tools_widget_2)
        self.quickaction_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quickaction_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quickaction_frame.setObjectName("quickaction_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.quickaction_frame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.quickactions2_pushButton = QtWidgets.QPushButton(self.quickaction_frame)
        self.quickactions2_pushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.quickactions2_pushButton.setFont(font)
        self.quickactions2_pushButton.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("icon/icons8-chevron-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon22.addPixmap(QtGui.QPixmap("icon/booster.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        
        self.quickactions2_pushButton.setIcon(icon22)
        self.quickactions2_pushButton.setIconSize(QtCore.QSize(25, 25))
        self.quickactions2_pushButton.setCheckable(True)
        self.quickactions2_pushButton.setAutoExclusive(True)
        self.quickactions2_pushButton.setFlat(True)
        self.quickactions2_pushButton.setChecked(True)
        self.quickactions2_pushButton.setObjectName("quickactions2_pushButton")
        self.verticalLayout_11.addWidget(self.quickactions2_pushButton)
        self.quickaction_dropdown = QtWidgets.QFrame(self.quickaction_frame)
        self.quickaction_dropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quickaction_dropdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quickaction_dropdown.setObjectName("quickaction_dropdown")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.quickaction_dropdown)
        self.verticalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_10.setSpacing(4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.remove_bg = QtWidgets.QPushButton(self.quickaction_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.remove_bg.setFont(font)
        self.remove_bg.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("icon/icons8-remove-document-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_bg.setIcon(icon23)
        self.remove_bg.setIconSize(QtCore.QSize(25, 25))
        self.remove_bg.setCheckable(True)
        self.remove_bg.setFlat(True)
        self.remove_bg.setObjectName("remove_bg")
        self.verticalLayout_10.addWidget(self.remove_bg)
        self.blur_bg = QtWidgets.QPushButton(self.quickaction_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.blur_bg.setFont(font)
        self.blur_bg.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("icon/icons8-blur-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blur_bg.setIcon(icon24)
        self.blur_bg.setIconSize(QtCore.QSize(25, 25))
        self.blur_bg.setCheckable(True)
        self.blur_bg.setFlat(True)
        self.blur_bg.setObjectName("blur_bg")
        self.verticalLayout_10.addWidget(self.blur_bg)
        self.blackwhite_bg = QtWidgets.QPushButton(self.quickaction_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.blackwhite_bg.setFont(font)
        self.blackwhite_bg.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("icon/icons8-background-remover-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blackwhite_bg.setIcon(icon25)
        self.blackwhite_bg.setIconSize(QtCore.QSize(30, 30))
        self.blackwhite_bg.setCheckable(True)
        self.blackwhite_bg.setFlat(True)
        self.blackwhite_bg.setObjectName("blackwhite_bg")
        self.verticalLayout_10.addWidget(self.blackwhite_bg)
        self.verticalLayout_11.addWidget(self.quickaction_dropdown)
        self.verticalLayout_16.addWidget(self.quickaction_frame)
        self.paint_frame_12 = QtWidgets.QFrame(self.tools_widget_2)
        self.paint_frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.paint_frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.paint_frame_12.setObjectName("paint_frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.paint_frame_12)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.paint2_pushButton = QtWidgets.QPushButton(self.paint_frame_12)
        self.paint2_pushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.paint2_pushButton.setFont(font)
        self.paint2_pushButton.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("icon/icons8-chevron-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon26.addPixmap(QtGui.QPixmap("icon/paint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paint2_pushButton.setIcon(icon26)
        self.paint2_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.paint2_pushButton.setCheckable(True)
        self.paint2_pushButton.setAutoExclusive(True)
        self.paint2_pushButton.setFlat(True)
        self.paint2_pushButton.setChecked(True)
        self.paint2_pushButton.setObjectName("paint2_pushButton")
        self.verticalLayout_9.addWidget(self.paint2_pushButton)
        self.paint_dropdown = QtWidgets.QFrame(self.paint_frame_12)
        self.paint_dropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.paint_dropdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.paint_dropdown.setObjectName("paint_dropdown")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.paint_dropdown)
        self.verticalLayout_12.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_12.setSpacing(4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.brush = QtWidgets.QPushButton(self.paint_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.brush.setFont(font)
        self.brush.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("icon/icons8-brush-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brush.setIcon(icon27)
        self.brush.setIconSize(QtCore.QSize(25, 25))
        self.brush.setCheckable(True)
        self.brush.setFlat(True)
        self.brush.setObjectName("brush")
        self.verticalLayout_12.addWidget(self.brush)
        self.eraser = QtWidgets.QPushButton(self.paint_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.eraser.setFont(font)
        self.eraser.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("icon/icons8-eraser-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eraser.setIcon(icon28)
        self.eraser.setIconSize(QtCore.QSize(30, 30))
        self.eraser.setCheckable(True)
        self.eraser.setFlat(True)
        self.eraser.setObjectName("eraser")
        self.verticalLayout_12.addWidget(self.eraser)
        self.verticalLayout_9.addWidget(self.paint_dropdown)
        self.verticalLayout_16.addWidget(self.paint_frame_12)
        self.transform_frame = QtWidgets.QFrame(self.tools_widget_2)
        self.transform_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transform_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transform_frame.setObjectName("transform_frame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.transform_frame)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.transform2_pushButton = QtWidgets.QPushButton(self.transform_frame)
        self.transform2_pushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.transform2_pushButton.setFont(font)
        self.transform2_pushButton.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("icon/icons8-chevron-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon29.addPixmap(QtGui.QPixmap("icon/transform.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        
        self.transform2_pushButton.setIcon(icon29)
        self.transform2_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.transform2_pushButton.setCheckable(True)
        self.transform2_pushButton.setAutoExclusive(True)
        self.transform2_pushButton.setFlat(True)
        self.transform2_pushButton.setChecked(True)
        self.transform2_pushButton.setObjectName("transform2_pushButton")
        self.verticalLayout_20.addWidget(self.transform2_pushButton)
        self.transform_dropdown = QtWidgets.QFrame(self.transform_frame)
        self.transform_dropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transform_dropdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transform_dropdown.setObjectName("transform_dropdown")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.transform_dropdown)
        self.verticalLayout_14.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_14.setSpacing(4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.rotation = QtWidgets.QPushButton(self.transform_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.rotation.setFont(font)
        self.rotation.setStyleSheet("QPushButton {\n"
"     height:25px;\n"                                    
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("icon/icons8-rotate-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotation.setIcon(icon30)
        self.rotation.setIconSize(QtCore.QSize(25, 25))
        self.rotation.setCheckable(True)
        self.rotation.setFlat(True)
        self.rotation.setObjectName("rotation")
        self.verticalLayout_14.addWidget(self.rotation)
        self.translation = QtWidgets.QPushButton(self.transform_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.translation.setFont(font)
        self.translation.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Optional: Adjust padding as needed */\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"}")
        self.translation.setIcon(icon17)
        self.translation.setIconSize(QtCore.QSize(30, 30))
        self.translation.setCheckable(True)
        self.translation.setFlat(True)
        self.translation.setObjectName("translation")
        self.verticalLayout_14.addWidget(self.translation)
        self.verticalLayout_20.addWidget(self.transform_dropdown)
        self.verticalLayout_16.addWidget(self.transform_frame)
        self.text2_PushButton = QtWidgets.QPushButton(self.tools_widget_2)
        self.text2_PushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.text2_PushButton.setFont(font)
        self.text2_PushButton.setStyleSheet("QPushButton {\n"
"     height:25px;\n"
"    text-align: left;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
" outline: none;\n"
"\n"
"\n"
"}")
        self.text2_PushButton.setIcon(icon7)
        self.text2_PushButton.setIconSize(QtCore.QSize(30, 30))
        self.text2_PushButton.setCheckable(True)
        self.text2_PushButton.setAutoExclusive(False)
        self.text2_PushButton.setFlat(True)
        self.text2_PushButton.setObjectName("text2_PushButton")
        self.verticalLayout_16.addWidget(self.text2_PushButton)
        # self.shapes2_pushButton = QtWidgets.QPushButton(self.tools_widget_2)
        # self.shapes2_pushButton.setEnabled(True)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(8)
        # font.setBold(True)
        # font.setWeight(75)
#         self.shapes2_pushButton.setFont(font)
#         self.shapes2_pushButton.setStyleSheet("QPushButton {\n"
# "     height:25px;\n"
# "    text-align: left;}\n"
# "QPushButton:hover{\n"
# "    background-color: rgb(80, 80, 80);\n"
# "   border-radius:5px;\n"
# "}\n"
# "QPushButton{\n"
# "border:none;\n"
# " outline: none;\n"
# "\n"
# "}")
        # self.shapes2_pushButton.setIcon(icon8)
        # self.shapes2_pushButton.setIconSize(QtCore.QSize(30, 30))
        # self.shapes2_pushButton.setCheckable(True)
        # self.shapes2_pushButton.setAutoExclusive(False)
        # self.shapes2_pushButton.setFlat(True)
        # self.shapes2_pushButton.setObjectName("shapes2_pushButton")
        # self.verticalLayout_16.addWidget(self.shapes2_pushButton)
        self.verticalLayout_18.addLayout(self.verticalLayout_16)
        spacerItem3 = QtWidgets.QSpacerItem(17, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem3)

        # Create QScrollArea and set its parent to self.centralwidget
        self.scroll_area_tools_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_area_tools_2.setWidgetResizable(False)  # Allow resizing of the widget inside the scroll area

        # Set vertical scrollbar policy
        self.scroll_area_tools_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area_tools_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)  # Disable horizontal scrollbar if needed

        # Add the tools_widget_2 to the QScrollArea
        self.scroll_area_tools_2.setWidget(self.tools_widget_2)
        self.scroll_area_tools_2.setFixedWidth(260)
#         self.scroll_area_tools_2.setStyleSheet("""
#     QScrollArea {
#         border: none;
#     }
# """)

 # Set the size policy of the widget inside the scroll area to not affect its width
        self.tools_widget_2.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)  # Fixed width, expanding height

       

        # Add the scroll area to your layout (for example, a gridLayout)
        self.gridLayout.addWidget(self.scroll_area_tools_2, 0, 1, 1, 1)  # Adjus 

        # self.gridLayout.addWidget(self.tools_widget_2, 0, 1, 1, 1)
        self.main_window = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_window.sizePolicy().hasHeightForWidth())
        self.main_window.setSizePolicy(sizePolicy)
        self.main_window.setStyleSheet("background-color: rgb(40,40,40);")
        self.main_window.setObjectName("main_window")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.zoom_menu = QtWidgets.QWidget(self.main_window)
        self.zoom_menu.setMinimumSize(QtCore.QSize(1200, 45))
        self.zoom_menu.setMaximumSize(QtCore.QSize(1200, 45))
        self.zoom_menu.setStyleSheet("QWidget{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(53, 53, 53);\n"
"}")
        self.zoom_menu.setObjectName("zoom_menu")
        self.layoutWidget = QtWidgets.QWidget(self.zoom_menu)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 220, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_38 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_38.sizePolicy().hasHeightForWidth())
        self.pushButton_38.setSizePolicy(sizePolicy)
        self.pushButton_38.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"}\n"
"\n"
"")
        # self.pushButton_38.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("icon/icons8-menu-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_38.setIcon(icon31)
        self.pushButton_38.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_38.setCheckable(True)
        self.pushButton_38.setChecked(False)
        self.pushButton_38.setAutoExclusive(False)
        self.pushButton_38.setAutoDefault(False)
        self.pushButton_38.setDefault(False)
        self.pushButton_38.setFlat(True)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout.addWidget(self.pushButton_38)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        # self.pushButton.setToolTipDuration(2)
        self.pushButton_38.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_38.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_38.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"}\n"
"")
        self.pushButton.setText("")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("icon/icons8-zoom-in-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon32)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        # self.pushButton_2.setToolTipDuration(2)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"border:none;\n"
"   border-radius:5px;\n"
"\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"}\n"
"")
        self.pushButton_2.setText("")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("icon/icons8-zoom-out-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon33)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setToolTipDuration(2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"}\n"
"")
        self.pushButton_3.setText("")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap("icon/icons8-reset-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon34)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_3.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"}\n"
"")
        self.verticalLayout_2.addWidget(self.zoom_menu)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_20 = QtWidgets.QPushButton(self.main_window)
        self.pushButton_20.setMinimumSize(QtCore.QSize(150, 25))
        self.pushButton_20.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("QPushButtons:checked{\n"
"background-color:white;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"\n"
"color:white;\n"
"}")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap("icon/icons8-properties-script-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon35.addPixmap(QtGui.QPixmap("icon/icons8-forward-24 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_20.setIcon(icon35)
        self.pushButton_20.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setAutoExclusive(False)
        self.pushButton_20.setChecked(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_5.addWidget(self.pushButton_20)
        self.frame_2 = QtWidgets.QFrame(self.main_window)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_21.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_21.setSpacing(5)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_3.setSpacing(0)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setMinimumSize(45, 45)  
        self.label_7.setMaximumSize(45, 45)  
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QLabel{\n"
"color:white\n"
"}")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(53, 53, 53);\n"
"border:none;\n"
"color:white;")
        self.lineEdit.setObjectName("lineEdit")
        # Set minimum and maximum sizes (optional)
        self.lineEdit.setMinimumSize(643, 30)
        self.lineEdit.setMaximumSize(643, 30)
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_21.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMinimumSize(50, 25)  
        self.label_5.setMaximumSize(50, 25)  
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel:hover{\n"
"    color: rgb(255, 167, 135);\n"
"    background-color: rgb(80, 80, 80);\n"
"   border-radius:5px;\n"
"}\n"
"QLabel{\n"
"color:white\n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)

        # Replace lineEdit_7 with QSpinBox
        self.spinBox_7 = QtWidgets.QSpinBox(self.frame_2)
        self.label_7.setMinimumSize(55, 25)  
        self.label_7.setMaximumSize(55, 25) 
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.spinBox_7.setFont(font)
        self.spinBox_7.setStyleSheet("background-color: rgb(53, 53, 53);\n"
                             "border:none;\n"
                             "color:white;")
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_7.setRange(0, 1000)  # Set range for the spinbox (adjust as needed)
        self.horizontalLayout_4.addWidget(self.spinBox_7)

        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMinimumSize(50, 25)  
        self.label_4.setMaximumSize(50, 25) 
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel:hover{\n"
                           "    color: rgb(255, 167, 135);\n"
                           "    background-color: rgb(80, 80, 80);\n"
                           "   border-radius:5px;\n"
                           "}\n"
                           "QLabel{\n"
                           "color:white\n"
                           "}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)

        # Replace lineEdit_2 with QSpinBox
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setStyleSheet("background-color: rgb(53, 53, 53);\n"
                             "border:none;\n"
                             "color:white;")
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_2.setRange(0, 1000)  # Set range for the spinbox (adjust as needed)
        self.horizontalLayout_4.addWidget(self.spinBox_2)

        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setMinimumSize(50, 25)  
        self.label_6.setMaximumSize(50, 25) 
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel:hover{\n"
                           "    color: rgb(255, 167, 135);\n"
                           "    background-color: rgb(80, 80, 80);\n"
                           "   border-radius:5px;\n"
                           "}\n"
                           "QLabel{\n"
                           "color:white\n"
                           "}")

        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)

# Replace lineEdit_8 with QComboBox
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setStyleSheet("""
    QComboBox {
        background-color: rgb(53, 53, 53);
        border: none;
        color: white;  /* Set the text color to white */
        height: 20px;  /* Increase the height of the combo box */
        padding: 2px;  /* Add padding for better alignment */
    }
    QComboBox::item{
        background-color: rgb(53, 53, 53);
        color: white;  /* Set the dropdown text color to white */
        selection-background-color: rgb(80, 80, 80);
        selection-color: white;
    }
""")
        self.comboBox_8.setObjectName("comboBox_8")

        # Add image format options to the ComboBox
        self.comboBox_8.addItems(["jpeg", "png", "gif", "tiff", "webp"]) # Extend with more formats if needed

        self.horizontalLayout_4.addWidget(self.comboBox_8)
        self.verticalLayout_21.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addWidget(self.frame_2)

        spacerItem4 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        # spacerItem5 = QtWidgets.QSpacerItem(18, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        # self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        # self.graphicsView = QtWidgets.QGraphicsView(self.main_window)
        # self.graphicsView.setMinimumSize(QtCore.QSize(1000, 650))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # self.graphicsView.setFont(font)
        # self.graphicsView.setStyleSheet("padding-left:10px;")
        # self.graphicsView.setObjectName("graphicsView")
        # self.horizontalLayout_6.addWidget(self.graphicsView)
      
        self.imageLabel = QtWidgets.QLabel(self.layoutWidget)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        # Set the size of the label to 600x600
        self.imageLabel.setFixedSize(1150, 760)

        # Set the border color to white
        # self.imageLabel.setStyleSheet("border: 2px solid white;")

        # Add the label to the layout
        self.horizontalLayout_6.addWidget(self.imageLabel)

        

        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        # spacerItem8 = QtWidgets.QSpacerItem(17, 229, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # self.verticalLayout_2.addItem(spacerItem8)


        self.scroll_area = QScrollArea(self.centralwidget)  # Pass centralwidget as the parent

        self.scroll_area.setWidgetResizable(True)

        # Create a new layout for the scrollable content inside QScrollArea
        self.scroll_widget = QWidget()  # The widget inside the scroll area
        self.scroll_area.setWidget(self.scroll_widget)  # Set the widget inside the scroll area
#         self.scroll_area.setStyleSheet("""
#     QScrollArea {
#         border: none;
#     }
# """)
        # Create a layout for the scrollable widget
        self.scroll_layout = QVBoxLayout(self.scroll_widget)
        self.scroll_layout.addWidget(self.main_window)  # Add your main widget to the scrollable layout
        self.gridLayout.addWidget(self.scroll_area, 0, 2, 1, 1)  # Add scroll area to the grid layout


        # self.gridLayout.addWidget(self.main_window, 0, 2, 1, 1)

        AuraEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AuraEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1930, 22))
        self.menubar.setObjectName("menubar")
        self.menubar.setStyleSheet("""
QMenuBar {
    background-color: rgb(53,53,53); /* Optional: to set the background color of the menubar */
}
QMenuBar::item:selected {
    color: rgb(255, 167, 135); /* Hover text color for dropdown menu items */
    background-color: rgb(80, 80, 80); /* Highlight background for hovered dropdown items */
    border-radius:5px;
}

QMenuBar::item {
    color: white; /* Set the menu item text color */
}

QMenu::item {
    color: white; /* Set the menu dropdown item text color */
}
                                   
QMenu::item:selected {
    color: rgb(255, 167, 135); /* Hover text color for dropdown menu items */
    background-color: rgb(80, 80, 80); /* Highlight background for hovered dropdown items */
    border-radius:5px;
}
""")
        

                # Add the new property widget
        self.property_widget = QtWidgets.QWidget(self.centralwidget)
        self.property_widget.setObjectName("property_widget")
        self.property_widget.setStyleSheet("background-color: rgb(53, 53, 53); color: white;")
        self.property_widget.setSizePolicy(
        QtWidgets.QSizePolicy.Preferred,
        QtWidgets.QSizePolicy.Expanding
        )

        # Set minimum and maximum sizes
        self.property_widget.setMinimumWidth(300)
        self.property_widget.setMinimumHeight(890)
        self.property_widget.setMaximumWidth(300)
        self.property_widget.setMaximumHeight(890)

        # Add QTreeWidget for dynamic filter parameters
        self.tree_widget = QtWidgets.QTreeWidget(self.property_widget)
        self.tree_widget.setHeaderLabels(["Parameter", "Value"])
        self.tree_widget.setColumnWidth(0, 150)  # Adjust column width for parameter names
        self.tree_widget.setStyleSheet("QTreeWidget::item { margin: 5px; }")

        # Add the QTreeWidget to the layout
        property_layout = QtWidgets.QVBoxLayout(self.property_widget)
        property_layout.addWidget(self.tree_widget)

        # Add property_widget to the grid layout at a specific position
        self.gridLayout.addWidget(self.property_widget, 0, 3, 1, 1)

        # Set up the central widget
        AuraEdit.setCentralWidget(self.centralwidget)

        


        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        AuraEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AuraEdit)
        self.statusbar.setObjectName("statusbar")
        AuraEdit.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(AuraEdit)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(AuraEdit)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(AuraEdit)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(AuraEdit)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionCut = QtWidgets.QAction(AuraEdit)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(AuraEdit)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(AuraEdit)
        self.actionPaste.setObjectName("actionPaste")
        self.actionAbout = QtWidgets.QAction(AuraEdit)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFind = QtWidgets.QAction(AuraEdit)
        self.actionFind.setObjectName("actionFind")
        self.actionFind_next = QtWidgets.QAction(AuraEdit)
        self.actionFind_next.setObjectName("actionFind_next")
        self.actionReplace = QtWidgets.QAction(AuraEdit)
        self.actionReplace.setObjectName("actionReplace")
        self.actionClose = QtWidgets.QAction(AuraEdit)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout_2 = QtWidgets.QAction(AuraEdit)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.action = QtWidgets.QAction(AuraEdit)
        self.action.setObjectName("action")
        self.actionGuassian_blur = QtWidgets.QAction(AuraEdit)
        self.actionGuassian_blur.setObjectName("actionGuassian_blur")
        self.actionNoise = QtWidgets.QAction(AuraEdit)
        self.actionNoise.setObjectName("actionNoise")
        self.actionDistort = QtWidgets.QAction(AuraEdit)
        self.actionDistort.setObjectName("actionDistort")
        self.actionSharpen = QtWidgets.QAction(AuraEdit)
        self.actionSharpen.setObjectName("actionSharpen")
        self.actionSketch = QtWidgets.QAction(AuraEdit)
        self.actionSketch.setObjectName("actionSketch")
        self.actionMean_Filter = QtWidgets.QAction(AuraEdit)
        self.actionMean_Filter.setObjectName("actionMean_Filter")
        self.actionEdge_Detection = QtWidgets.QAction(AuraEdit)
        self.actionEdge_Detection.setObjectName("actionEdge_Detection")
        self.sobel_Filter = QtWidgets.QAction(AuraEdit)
        self.sobel_Filter.setObjectName("Sobel_Filter")
        self.linear_Filter = QtWidgets.QAction(AuraEdit)
        self.linear_Filter.setObjectName("Linear_Filter")
        self.actionAbout_3 = QtWidgets.QAction(AuraEdit)
        self.actionAbout_3.setObjectName("actionAbout_3")
        self.actionTools = QtWidgets.QAction(AuraEdit)
        self.actionTools.setObjectName("actionTools")
        self.actionPropertiies = QtWidgets.QAction(AuraEdit)
        self.actionPropertiies.setObjectName("actionPropertiies")
        self.actionMain_Window = QtWidgets.QAction(AuraEdit)
        self.actionMain_Window.setObjectName("actionMain_Window")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionGuassian_blur)
        self.menuAbout.addAction(self.actionNoise)
        self.menuAbout.addAction(self.actionDistort)
        self.menuAbout.addAction(self.actionSharpen)
        self.menuAbout.addAction(self.actionSketch)
        self.menuAbout.addAction(self.actionMean_Filter)
        self.menuAbout.addAction(self.actionEdge_Detection)
        self.menuAbout.addAction(self.sobel_Filter)
        self.menuAbout.addAction(self.linear_Filter)
        self.menuWindow.addAction(self.actionTools)
        self.menuWindow.addAction(self.actionPropertiies)
        self.menuWindow.addAction(self.actionMain_Window)
        self.menuHelp.addAction(self.actionAbout_3)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        


        self.retranslateUi(AuraEdit)
        self.text2_PushButton.toggled['bool'].connect(self.text1_pushButton.setChecked) # type: ignore
        # self.shapes2_pushButton.toggled['bool'].connect(self.shape1_pushButton.setChecked) # type: ignore
        # self.size2_pushButton.toggled['bool'].connect(self.size1_pushButton.setChecked) # type: ignore
        self.quickactions2_pushButton.toggled['bool'].connect(self.quickaction1_pushButton.setChecked) # type: ignore
        self.adjust2_pushButton.toggled['bool'].connect(self.adjust1_pushButton.setChecked) # type: ignore
        self.paint2_pushButton.toggled['bool'].connect(self.paint1_pushButton.setChecked) # type: ignore
        self.transform2_pushButton.toggled['bool'].connect(self.transform_dropdown.setHidden) # type: ignore
        # self.size2_pushButton.toggled['bool'].connect(self.size_dropdown.setHidden) # type: ignore
        self.transform2_pushButton.toggled['bool'].connect(self.transform1_pushButton.setChecked) # type: ignore
        self.quickactions2_pushButton.toggled['bool'].connect(self.quickaction_dropdown.setHidden) # type: ignore
        # self.select2_pushButton.toggled['bool'].connect(self.select1_pushButton.setChecked) # type: ignore
        self.adjust2_pushButton.toggled['bool'].connect(self.adjust_dropdown.setHidden) # type: ignore
        self.retouch2_pushButton.toggled['bool'].connect(self.retouch_dropdown.setHidden) # type: ignore
        self.paint2_pushButton.toggled['bool'].connect(self.paint_dropdown.setHidden) # type: ignore
        # self.select2_pushButton.toggled['bool'].connect(self.select_dropdown.setHidden) # type: ignore
        self.retouch2_pushButton.toggled['bool'].connect(self.retouch1_pushButton.setChecked) # type: ignore
        self.pushButton_38.toggled['bool'].connect(self.scroll_area_tools_2.setHidden) # type: ignore
        self.pushButton_38.toggled['bool'].connect(self.tools_widget.setVisible) # type: ignore
        self.pushButton_20.toggled['bool'].connect(self.frame_2.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AuraEdit)

    def retranslateUi(self, AuraEdit):
        _translate = QtCore.QCoreApplication.translate
        AuraEdit.setWindowTitle(_translate("AuraEdit", "MainWindow"))
        # self.size2_pushButton.setText(_translate("AuraEdit", "Size and Position"))
        # self.move.setText(_translate("AuraEdit", "Move"))
        # self.crop.setText(_translate("AuraEdit", "Crop"))
        # self.resizing.setText(_translate("AuraEdit", "Resizing"))
        self.adjust2_pushButton.setText(_translate("AuraEdit", "Adjust"))
        self.brightness.setText(_translate("AuraEdit", "Brightness/Constrast"))
        self.saturation.setText(_translate("AuraEdit", "Saturation"))
        # self.select2_pushButton.setText(_translate("AuraEdit", "Select"))
        # self.select_subject.setText(_translate("AuraEdit", "Select Subject"))
        # self.object_selection.setText(_translate("AuraEdit", "Object Selection"))
        self.retouch2_pushButton.setText(_translate("AuraEdit", "Retouch"))
        self.lighten.setText(_translate("AuraEdit", "Lighten"))
        self.darken.setText(_translate("AuraEdit", "Darken"))
        self.quickactions2_pushButton.setText(_translate("AuraEdit", "Quick actions"))
        self.remove_bg.setText(_translate("AuraEdit", "Remove Background"))
        self.blur_bg.setText(_translate("AuraEdit", "Blur Background"))
        self.blackwhite_bg.setText(_translate("AuraEdit", "Black/white background"))
        self.paint2_pushButton.setText(_translate("AuraEdit", "Paint"))
        self.brush.setText(_translate("AuraEdit", "Brush"))
        self.eraser.setText(_translate("AuraEdit", "Eraser"))
        self.transform2_pushButton.setText(_translate("AuraEdit", "Transforms"))
        self.rotation.setText(_translate("AuraEdit", "Rotation"))
        self.translation.setText(_translate("AuraEdit", "Translation"))
        self.text2_PushButton.setText(_translate("AuraEdit", "Text"))
        # self.shapes2_pushButton.setText(_translate("AuraEdit", "Shapes"))
        self.pushButton.setToolTip(_translate("AuraEdit", "Zoom in"))
        self.pushButton_2.setToolTip(_translate("AuraEdit", "Zoom in"))
        self.pushButton_3.setToolTip(_translate("AuraEdit", "Zoom in"))
        self.pushButton_20.setText(_translate("AuraEdit", "Properties"))
        self.label_7.setText(_translate("AuraEdit", "Name"))
        self.label_5.setText(_translate("AuraEdit", "Width"))
        self.label_4.setText(_translate("AuraEdit", "Height"))
        self.label_6.setText(_translate("AuraEdit", "Format"))
        self.menuFile.setTitle(_translate("AuraEdit", "File"))
        self.menuEdit.setTitle(_translate("AuraEdit", "Edit"))
        self.menuAbout.setTitle(_translate("AuraEdit", "Filters"))
        self.menuWindow.setTitle(_translate("AuraEdit", "View"))
        self.menuHelp.setTitle(_translate("AuraEdit", "Help"))
        self.actionOpen.setText(_translate("AuraEdit", "Open"))
        self.actionNew.setText(_translate("AuraEdit", "New"))
        self.actionSave.setText(_translate("AuraEdit", "Save"))
        self.actionSave_as.setText(_translate("AuraEdit", "Save as"))
        self.actionCut.setText(_translate("AuraEdit", "Cut"))
        self.actionCopy.setText(_translate("AuraEdit", "Copy"))
        self.actionPaste.setText(_translate("AuraEdit", "Paste"))
        self.actionAbout.setText(_translate("AuraEdit", "Grayscale Filter"))
        self.actionFind.setText(_translate("AuraEdit", "Find"))
        self.actionFind_next.setText(_translate("AuraEdit", "Find next"))
        self.actionReplace.setText(_translate("AuraEdit", "Replace"))
        self.actionClose.setText(_translate("AuraEdit", "Close"))
        self.actionAbout_2.setText(_translate("AuraEdit", "About "))
        self.actionAbout_2.setToolTip(_translate("AuraEdit", "<html><head/><body><p><br/></p></body></html>"))
        self.action.setText(_translate("AuraEdit", "About"))
        self.action.setIconText(_translate("AuraEdit", "About"))
        self.actionGuassian_blur.setText(_translate("AuraEdit", "Guassian Blur"))
        self.actionNoise.setText(_translate("AuraEdit", "Noise"))
        self.actionDistort.setText(_translate("AuraEdit", "Distort"))
        self.actionSharpen.setText(_translate("AuraEdit", "Sharpen"))
        self.actionSketch.setText(_translate("AuraEdit", "Sketch"))
        self.actionMean_Filter.setText(_translate("AuraEdit", "Mean Filter"))
        self.actionEdge_Detection.setText(_translate("AuraEdit", "Edge Detection"))
        self.sobel_Filter.setText(_translate("AuraEdit", "Sobel Filter"))
        self.linear_Filter.setText(_translate("AuraEdit", "Linear Filter"))
        self.actionAbout_3.setText(_translate("AuraEdit", "About"))
        self.actionTools.setText(_translate("AuraEdit", "Tools"))
        self.actionPropertiies.setText(_translate("AuraEdit", "Properties"))
        self.actionMain_Window.setText(_translate("AuraEdit", "Main Window"))
